# Generated by Django 4.1.7 on 2023-02-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='firstname',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='lastname',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
    ]
